### PR TITLE
Bugfix: singularity instructions.

### PR DESCRIPTION
**Pull request by guacke**

### CODE REVIEW

**Comment by emielvb** [comment]
Pulling the singularity bootcamp image works now.

However, running notebooks still gives issues:
image
This is not due to the period in the filename, as integrals.ipynb gives a similar error:
image

**Review by emielvb — CHANGES_REQUESTED** [review]
see previous comment.

**Review by guacke — COMMENTED** [review]
Fixed.

**Review by emielvb — APPROVED** [review]
Looks good

**Pull request merged**
